name: Test and Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            python: [3.7, 3.8, 3.9, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v --doctest-modules --ignore alt/scheme/ribbit
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 nand/ *.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 nand/ *.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
